### PR TITLE
Adds option to return a second array with removed items

### LINKED ISSUE #2: Record removed array items
Thanks for this utility!

I'd like to be able to record which items are removed from the array. Would it be feasible to be able to optionally return two arrays? The first array with items removed and the second one containing only the removed items.

### PR DESCRIPTION
**Pull request by mikemcbride**
Allows passing a second parameter to the function that would return a second array containing the removed items:

```js
const arr = ['cat', 'dog', 'pig', 'cat', 'monkey', 'pig'] // cat and pig are duplicates
const withoutDupes = uniq(arr, { includeDuplicates: true })
// [ ['cat', 'dog', 'pig', 'monkey'], ['cat', 'pig'] ]
```

@dgwyer does this fix #2?

### CODE REVIEW

**Comment by dgwyer** [comment]
That looks good, thanks!

**Comment by mikemcbride** [comment]
Great! It'll be available in version `1.1.0`

**Comment by dgwyer** [comment]
Thanks for the response and quick turnaround Mike. Have a gold star for your efforts! :)

**Comment by mikemcbride** [comment]
You are quite welcome sir! Glad you find it useful!

**Comment by dgwyer** [comment]
It's a nice little utility.

What other things are you working on at the moment?

**Comment by mikemcbride** [comment]
I have a few other utility things that I've done that are fun and in a similar vein to this, but mostly just stuff for work. We do a lot of Vue and Node at my company and I've been enjoying that a lot.

Some fun utilities you might enjoy:
https://github.com/mikemcbride/convert-color-cli
https://github.com/mikemcbride/object-has-value

I also have been working off and on on an online sudoku solver that's been pretty challenging and fun:

https://github.com/mikemcbride/vue-sudoku

**Comment by dgwyer** [comment]
Nice! Keep up the good work Mike.

**Pull request merged**
